website/__init__.py
from flask import Flask
from os import path

def create_app():
    app = Flask(__name__)

    from .views import views
    app.register_blueprint(views, url_prefix='/')

    return app

website/views.py
import os
from flask import Blueprint, render_template, request, json, url_for

import pickle
import numpy as np

models_path = os.path.join(os.path.dirname(__file__), 'ml_models')
totalCases = pickle.load(open(models_path + '/total_cases.pickle', 'rb'))
totalDeaths = pickle.load(open(models_path + '/total_deaths.pickle', 'rb'))


views = Blueprint('views', __name__, static_folder="static")

data = json.load(open(os.path.join(views.static_folder, 'data.json')))
columns = data['columns']
locations = columns[3:]


def getPrediction(location, year, month, day):
    loc_index = columns.index(location)
    
    x = np.zeros(len(columns))
    x[0] = year
    x[1] = month
    x[2] = day

    if loc_index >= 0:
        x[loc_index] = 1
    print(x)

    return {
        'total_cases': int(totalCases.predict([x])[0])*1000,
        'total_deaths': int(totalDeaths.predict([x])[0])*1000,
    }


@views.route('/', methods=['GET','POST'])
def index():
    if request.method == "POST":
        location = request.form['location']
        date = request.form['date']
        day, month, year = date.split("-")
        message = getPrediction(location, year, month, day)
        message['location'] = location
        message['date'] = date
        return render_template('index.html', locations=locations, message=message)
    return render_template('index.html', locations=locations)

website/templates/index.html
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Covid Cases Predictor</title>

    <!-- CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">

    <!-- JavaScript -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body class="row" style="margin-bottom: 0;">
    <nav>
        <div class="nav-wrapper">
            <a href="#" class="brand-logo center">Covid Cases Predictor</a>
        </div>
    </nav>
    <div class="col s12 m6 hide-on-small-only" id="bg"></div>
    <div class="col s12 m6">
        {% include 'predict.html' %}
    </div>
    <script type="text/javascript" src="{{ url_for('static', filename='main.js') }}"></script>
    {% if message %}
    {% include 'result.html' %}
    <script>
        $(document).ready(function () {
            $('.modal#result').modal('open');
        });
    </script>
    {% endif %}
</body>

</html>

website/templates/predict.html
<form class="col s12" method="POST" action="{{ url_for('views.index') }}">
    <div class="row valign-wrapper">
        <div class="col s12 m6 l4">
            <label for="location" class="btn-large waves-effect waves-light indigo">Location</label>
        </div>
        <div class="col s12 m6 l8 valign-wrapper">
            <select id="location" name="location">
                <option value="" disabled selected>Choose location</option>
                {% for location in locations %}
                <option value="{{ location }}">{{ location }}</option>
                {% endfor %}
            </select>
        </div>
    </div>
    <div class="row valign-wrapper">
        <div class="col s12 m6 l4">
            <label for="date" class="btn-large waves-effect waves-light indigo">Date</label>
        </div>
        <div class="col s12 m6 l8 valign-wrapper">
            <input type="text" id="date" name="date" class="datepicker">
        </div>
    </div>
    <div class="row center-align" style="margin-bottom: 0;">
        <div class="col s12">
            <button class="btn-large waves-effect waves-light green modal-trigger" data-target="result" type="submit"
                style="width: auto;">Get prediction</button>
        </div>
    </div>
</form>

website/templates/result.html
<div id="result" class="modal bottom-sheet">
    <div class="modal-content">
        <div style="display: flex; justify-content: space-between;">
            <h3 class="header">Our Prediction</h3>
            <button class="btn-floating modal-close waves-effect waves-light right red"><i
                    class="material-icons">close</i></button>
        </div>
        <div class="center" id="input" style="width: 60%; margin: 0 auto; font-size: 20px; display: flex; justify-content: space-between;">
        </div>
        <table class="centered responsive-table">
            <thead>
                <tr>
                    <th>Location</th>
                    <th>Date</th>
                    <th>Total Cases</th>
                    <th>Total Deaths</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>{{ message.location }}</td>
                    <td>{{ message.date }}</td>
                    <td>{{ message.total_cases }}</td>
                    <td>{{ message.total_deaths }}</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>